USE db;

-- CUSTOM FUNCTIONS.

-- FUNCTIONS DEFINTION AND DECLARATION.

DELIMITER $$
CREATE FUNCTION ADDITION(A INT, B INT) 
RETURNS INT 
DETERMINISTIC
BEGIN
       RETURN A + B;
       
END $$
DELIMITER ;

SELECT ADDITION(10, 5);

DELIMITER $$

CREATE FUNCTION ODD_EVEN_CHECKER(N INT)
RETURNS TEXT
DETERMINISTIC
BEGIN
      IF N % 2 = 0
      THEN RETURN 'EVEN';
      ELSE RETURN 'ODD';
      END IF;
END $$
DELIMITER ;

SELECT NUMBER,
ODD_EVEN_CHECKER(NUMBER) AS ODD_EVEN
FROM
(
SELECT 1 AS NUMBER
UNION
SELECT 2 AS NUMBER
UNION
SELECT 3 AS NUMBER
UNION
SELECT 4 AS NUMBER
UNION
SELECT 5 AS NUMBER
) AS T2;

SELECT 
      DISTINCT work_year,
      ODD_EVEN_CHECKER(work_year) AS ODD_EVEN
FROM salaries;

-- NON DETERMINISTIC FUNCTION

SET GLOBAL
LOG_BIN_TRUST_FUNCTION_CREATORS = 1;

DELIMITER $$

CREATE FUNCTION GET_RANDOM_NUMBER(STARTING_RANGE INT, ENDING_RANGE INT)
RETURNS INT
NOT DETERMINISTIC
BEGIN
    RETURN FLOOR(STARTING_RANGE + RAND() * (ENDING_RANGE - STARTING_RANGE + 1));
END $$

DELIMITER ;

SELECT GET_RANDOM_NUMBER(10, 15);