USE db;

-- CUSTOM FUNCTIONS.

-- FUNCTIONS DEFINTION AND DECLARATION.

DELIMITER $$
CREATE FUNCTION ADDITION(A INT, B INT) 
RETURNS INT 
DETERMINISTIC
BEGIN
       RETURN A + B;
       
END $$
DELIMITER ;

SELECT ADDITION(10, 5);

DELIMITER $$

CREATE FUNCTION ODD_EVEN_CHECKER(N INT)
RETURNS TEXT
DETERMINISTIC
BEGIN
      IF N % 2 = 0
      THEN RETURN 'EVEN';
      ELSE RETURN 'ODD';
      END IF;
END $$
DELIMITER ;

SELECT NUMBER,
ODD_EVEN_CHECKER(NUMBER) AS ODD_EVEN
FROM
(
SELECT 1 AS NUMBER
UNION
SELECT 2 AS NUMBER
UNION
SELECT 3 AS NUMBER
UNION
SELECT 4 AS NUMBER
UNION
SELECT 5 AS NUMBER
) AS T2;

SELECT 
      DISTINCT work_year,
      ODD_EVEN_CHECKER(work_year) AS ODD_EVEN
FROM salaries;