USE db;

-- FUNCTIONS.

-- 1. NUMERIC FUNCTION.
-- BASIC mathematical function (ABS, DIV, MOD, PI)

SELECT -5 AS ORIGINAL_VALUE,
ABS(-5) AS ABSOLUTE_VALUE; 

CREATE TABLE ABSOLUTE_VALUE
AS
SELECT -5 AS ORIGINAL_VALUE
UNION ALL
SELECT 10 AS ORIGINAL_VALUE
UNION ALL
SELECT -15 AS ORIGINAL_VALUE
UNION ALL
SELECT 500 AS ORIGINAL_VALUE
UNION ALL
SELECT -50 AS ORIGINAL_VALUE;

SELECT * FROM ABSOLUTE_VALUE;

SELECT ORIGINAL_VALUE,
ABS(ORIGINAL_VALUE) AS
ABSOLUTE_VALUE
FROM ABSOLUTE_VALUE;

SELECT -500 AS CURRENT_DATA,
ABS(-500) AS NEW_DATA;

-- DIV, MOD

SELECT 100 AS DIVIDEND, 13 AS
DIVISOR, 100 DIV 13 AS QUOTIENT,
MOD(100, 13) AS REMAINDER;

-- PI().

SELECT PI();

-- POWER FUNCTIONS.

SELECT POWER(10, 2) AS SQUARE_OF_10;

SELECT SQRT(100) AS
SQUARE_ROOT_OF_100;

SELECT POWER(100, 1/2) AS
SQUARE_ROOT_OF_100;

-- ROUNDING FUNCTION (FLOOR, CEILING, TRUNCATE, ROUND)

SELECT PI(), FLOOR(PI()),
CEILING(PI());

-- ROUND AND TRUNCATE.

SELECT 
   7.25 AS ORIGINAL_NUMBER,
   TRUNCATE(7.51, 0) AS
   TRUNCATED_VALUE,
   ROUND(7.51, 0) AS
   ROUNDED_VALUE;
   
   CREATE TABLE NUMBERS 
   AS
   SELECT 10 AS N1, 20 AS N2, 30 AS N3
   UNION ALL
   SELECT 30 AS N1, 20 AS N2, 10 AS N3
   UNION ALL
   SELECT 109 AS N1, 201 AS N2, 340 AS N3
   UNION ALL
   SELECT  110 AS N1, 220 AS N2, 130 AS N3
   UNION ALL 
   SELECT 910 AS N1, 220 AS N2, 230 AS N3;
   
   SELECT * FROM NUMBERS; 
   
   SELECT MAX(N1), MAX(N2), MAX(N3)
   FROM NUMBERS;
   
   SELECT MIN(N1), MIN(N2), MIN(N3)
   FROM NUMBERS;   
   
   SELECT * , GREATEST(1, N2, N3)
   AS ROW_WISE_MAX, LEAST(N1, N2, N3) AS ROW_WISE_MIN
   FROM NUMBERS;
   
   SELECT *, GREATEST(N1, N2, N3)
   AS ROW_WISE_MAX
   FROM NUMBERS;
   
   