USE db;

-- STRING FUNCTIONS.

-- STRING MANIPULATION.
-- (CONCAT, CONCAT_WS, INSERT, REPLACE)

CREATE TABLE HOKAGES AS
SELECT 'HashiRama' AS FIRST_NAME,
'Senju' AS LAST_NAME
UNION ALL
SELECT 'TobiRama' AS FIRST_NAME,
'Senju' AS LAST_NAME
UNION ALL
SELECT 'Hiruzen' AS FIRST_NAME,
'Sarutobi' AS LAST_NAME
UNION ALL
SELECT 'Minato' AS FIRST_NAME,
'Namikaze' AS LAST_NAME
UNION ALL
SELECT 'Tsunade' AS FIRST_NAME,
'Senju' AS LAST_NAME
UNION ALL
SELECT 'Kakashi' AS FIRST_NAME,
'Hatake' AS LAST_NAME
UNION ALL
SELECT 'Naruto' AS FIRST_NAME,
'Uzumaki' AS LAST_NAME
UNION ALL
SELECT 'Shikamaru' AS FIRST_NAME,
'Nara' AS LAST_NAME;

SELECT * FROM HOKAGES;

SELECT *, CONCAT(FIRST_NAME, ' ',
LAST_NAME) AS FULL_NAME
FROM HOKAGES;

CREATE TABLE QUOTE AS
SELECT "CHANGE" AS PART_1, "IS" AS
PART_2, "IMPOSSIBLE" AS PART_3,
"IN" AS PART_4, "THIS" AS PART_5,
"FOG" AS PART_6, "OF" AS PART_7,
"IGNORANCE" AS PART_8;

SELECT * FROM QUOTE;

SELECT *, CONCAT(PART_1, " ", PART_2, " ", PART_3, " ", PART_4, " ", 
PART_5, " ", PART_6, " ", PART_7, " ", PART_8) AS FINAL_QUOTE
FROM QUOTE;

SELECT *, CONCAT_WS(" ", PART_1, PART_2, PART_3, PART_4, PART_5,
PART_6, PART_7, PART_8) AS FINAL_QUOTE
FROM QUOTE;

-- NARUTO SHIPPUDEN - THE TALE OF NARUTO UZUMAKI

SELECT 
    CONCAT(CONCAT('NARUTO', ' ',
'SHIPPUDEN'),
             ' - ',
             CONCAT_WS(' ',
                     'THE',
                     'TALE',
                     'OF',
                     'NARUTO',
                     'UZUMAKI')) AS
SHIPPUDEN;

SELECT CONCAT_WS(" ", "NARUTO",
'SHIPPUDEN', "-", 'THE', 'TALE',
'OF', 'NARUTO', 'UZUMAKI') AS
SHIPPUDEN;

-- INSERT FUNCTION.

SELECT 
     "HASHIRAMA SENJU" AS 
LORD_FIRST,
          INSERT ("HASHIRAMA SENJU", 
          1, 4, "TOB") AS LORD_SECOND;
          
-- REPLACE 

SELECT *
FROM HOKAGES;

SELECT 
       "BANANA" AS MARDANA,
       REPLACE("BANANA", "NANA",
       "NANI") AS MARDANI;

-- STRING LENGTH AND PADDING
-- (LENGTH, CHAR_LENGTH, CHARACTER_LENGTH, LPAD, RPAD)

SELECT  
      "MADARA UCHIHA" AS
      GHOST_OF_THE_UCHIHA,
             LENGTH("MADARA UCHIHA") AS
      LENGTH, 
            CHAR_LENGTH("MADARA UCHIHA") AS
            LENGTH,
      CHARACTER_LENGTH("MADARA UCHIHA") AS LENGTH;
      
SELECT 
      "MADARA UCHIHA THE GHOST OF THE UCHIHA" AS ORIGINAL_STRING,
      
      LENGTH("MADARA UCHIHA THE GHOST OF THE UCHIHA") AS LENGTH,
      
      REPLACE("MADARA UCHIHA THE GHOST OF THE UCHIHA", " ", " "),
      
      LENGTH(REPLACE("MADARA UCHIHA THE GHOST OF THE UCHIHA", " ", 
      " "));
      
SELECT *,
     (LENGTH(ORIGINAL_STRING) - 
     LENGTH(STRING_WITHOUT_SPACES)) AS 
     NUMBER_OF_SPACES
     FROM
     (
      SELECT 
            "MADARA UCHIHA THE GHOST OF THE UCHIHA" AS ORIGINAL_STRING,
            REPLACE("MADARA UCHIHA THE GHOST OF THE UCHIHA", " ", " ") AS
            STRING_WITHOUT_SPACES
     ) AS T;
     
     
SELECT 
      "MADARA UCHIHA THE GHOST OF THE UCHIHA" AS ORIGINAL_STRING,
      REPLACE("MADARA UCHIHA THE GHOST OF THE UCHIHA", " ", " ") AS
      STRING_WITHOUT_SPACES;
      
-- PADDING (BINARY VALUES)

SELECT 
       '33' AS DECIMAL_VALUE,
       '100001' AS BINARY_VALUE,
       LPAD('100001', 8, 0) AS
       LEFT_PADDED_VALUE,
          RPAD('100001',8, 0) AS
          RIGHT_PADDED_VALUE;
          
          
-- STRING CASE  FUNCTIONS
-- (LOWER/LCASE, UPPER/UCASE)

-- SUBSTRING FUNCTIONS
-- (LEFT, RIGHT MID, SUBSTR, SUBSTRING, SUBSTRING_INDEX)
