/* DDL, DML, DCL --> DATA DEFINTION LANGUAGES, DATA MANIPULATION LANGUAGES & DATA CONTROL LANGUAGES */

USE db;

-- KEYWORDS

-- TABLE CREATION (DDL).

CREATE TABLE employees(
EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
EMP_NAME VARCHAR(50),
EMP_AGE INT,
EMP_SALARY DECIMAL (10, 2)
); 

-- INSERT SOME ENTRIES INTO THE TABLE (DML)

INSERT INTO EMPLOYEES(EMP_NAME, EMP_AGE, EMP_SALARY) 
VALUES('AFAN ASLAM SHAIKH', 20, 100000); 

-- VIEW OF THE TABLE (DQL)

SELECT * FROM employees;

-- INSERT MULTIPLE ENTRIES INTO THE TABLE 

INSERT INTO EMPLOYEES(EMP_NAME, EMP_AGE, EMP_SALARY) 
VALUES 
('Nilesh Chandrabali Yadav', 22, 50000), 
('Md Nishad Ahmad', 22, 60000), 
('Siraj Ahmad', 26, 70000); 

-- INSERT ENTRIES FOR SELECTED COLUMNS 

INSERT INTO EMPLOYEES(EMP_NAME, EMP_SALARY) 
VALUES 
('Varun Vilas Dange', 80000), 
('Rishabh Manoj Yadav', 90000); 

-- ALTER TALBE (add column i.e. gender) (DDL) 

ALTER TABLE EMPLOYEES ADD COLUMN GENDER ENUM('MALE', 'FEMALE', 'OTHERS'); 

-- RENAME A COLUMN 

-- RENAMING A NEW COLUMN 

ALTER TABLE EMPLOYEES RENAME COLUMN GENDER TO EMP_GENDER; 

ALTER TABLE EMPLOYEES DROP COLUMN EMP_GENDER; 

-- CHANGE THE TABLE NAME 



RENAME TABLE EMPLOYEES TO EMPLOYEE_DETAILS;

SELECT * FROM EMPLOYEE_DETAILS;

-- UPDATE GENDER DETAILS;

UPDATE EMPLOYEE_DETAILS 
SET EMP_GENDER = 'MALE' 
WHERE EMP_ID <= 6;  

-- THIS CODE WILL NOT BE EXECUTED SINCE SAFE UPDATED MODES ARE ENABLED 

-- DISABLE SQL SAFE UPDATE MODE
SET SQL_SAFE_UPDATES = 0;

UPDATE EMPLOYEE_DETAILS 
SET EMP_AGE = 22 
WHERE EMP_NAME LIKE 'VARUN%'; 

SELECT * FROM EMPLOYEE_DETAILS;

UPDATE EMPLOYEE_DETAILS 
SET EMP_SALARY = 
	CASE 
		WHEN EMP_ID % 2 = 0 THEN EMP_SALARY * 1.2 
        ELSE EMP_SALARY * 1.1 
	END; 


-- DELETION ALL EMPLOYEES WHOSE SALARY IS LESS THAN 75K 

DELETE FROM EMPLOYEE_DETAILS 
WHERE EMP_SALARY <= 75000; 

SELECT * FROM EMPLOYEE_DETAILS;

-- DELETING ALL ENTRIES 
DELETE FROM EMPLOYEE_DETAILS; 

-- QUESTION : DELETE | TRUNCATE 

-- TRUNCATE 

TRUNCATE TABLE EMPLOYEE_DETAILS; 

-- ENABLE THE SAFE UPDATE MODE AGAIN 
SET  SQL_SAFE_UPDATES = 1;
SET  SQL_SAFE_UPDATES = 0;

UPDATE EMPLOYEE_DETAILS 
SET EMP_SALARY = 100000 
WHERE EMP_AGE BETWEEN 20 AND 25; 


SELECT * FROM EMPLOYEE_DETAILS;

-- DATA CONTROL LANGUAGE.

-- ID AND PASSWORD CREATION 

CREATE USER IF NOT EXISTS 'person_1'@'%' IDENTIFIED BY 'abc123';


-- CREATING A SAMPLE VIEW 

CREATE VIEW WFH_EMPLOYEES AS 
SELECT * FROM salaries 
WHERE remote_ratio = 100; 

-- GRANTING PRIVILEGE TO USER FOR A PARTICULAR VIEW 

GRANT SELECT ON WFH_EMPLOYEES TO 'person_1'@'%'; 

