USE db;

-- STRING FUNCTIONS.

-- STRING MANIPULATION.
-- (CONCAT, CONCAT_WS, INSERT, REPLACE)

CREATE TABLE HOKAGES AS
SELECT 'HashiRama' AS FIRST_NAME,
'Senju' AS LAST_NAME
UNION ALL
SELECT 'TobiRama' AS FIRST_NAME,
'Senju' AS LAST_NAME
UNION ALL
SELECT 'Hiruzen' AS FIRST_NAME,
'Sarutobi' AS LAST_NAME
UNION ALL
SELECT 'Minato' AS FIRST_NAME,
'Namikaze' AS LAST_NAME
UNION ALL
SELECT 'Tsunade' AS FIRST_NAME,
'Senju' AS LAST_NAME
UNION ALL
SELECT 'Kakashi' AS FIRST_NAME,
'Hatake' AS LAST_NAME
UNION ALL
SELECT 'Naruto' AS FIRST_NAME,
'Uzumaki' AS LAST_NAME
UNION ALL
SELECT 'Shikamaru' AS FIRST_NAME,
'Nara' AS LAST_NAME;

SELECT * FROM HOKAGES;

SELECT *, CONCAT(FIRST_NAME, ' ',
LAST_NAME) AS FULL_NAME
FROM HOKAGES;

CREATE TABLE QUOTE AS
SELECT "CHANGE" AS PART_1, "IS" AS
PART_2, "IMPOSSIBLE" AS PART_3,
"IN" AS PART_4, "THIS" AS PART_5,
"FOG" AS PART_6, "OF" AS PART_7,
"IGNORANCE" AS PART_8;

SELECT * FROM QUOTE;

SELECT *, CONCAT(PART_1, " ", PART_2, " ", PART_3, " ", PART_4, " ", 
PART_5, " ", PART_6, " ", PART_7, " ", PART_8) AS FINAL_QUOTE
FROM QUOTE;

SELECT *, CONCAT_WS(" ", PART_1, PART_2, PART_3, PART_4, PART_5,
PART_6, PART_7, PART_8) AS FINAL_QUOTE
FROM QUOTE;

-- NARUTO SHIPPUDEN - THE TALE OF NARUTO UZUMAKI

SELECT 
    CONCAT(CONCAT('NARUTO', ' ',
'SHIPPUDEN'),
             ' - ',
             CONCAT_WS(' ',
                     'THE',
                     'TALE',
                     'OF',
                     'NARUTO',
                     'UZUMAKI')) AS
SHIPPUDEN;

SELECT CONCAT_WS(" ", "NARUTO",
'SHIPPUDEN', "-", 'THE', 'TALE',
'OF', 'NARUTO', 'UZUMAKI') AS
SHIPPUDEN;

-- INSERT FUNCTION.

SELECT 
     "HASHIRAMA SENJU" AS 
LORD_FIRST,
          INSERT ("HASHIRAMA SENJU", 
          1, 4, "TOB") AS LORD_SECOND;
          
-- REPLACE 

SELECT *
FROM HOKAGES;

SELECT 
       "BANANA" AS MARDANA,
       REPLACE("BANANA", "NANA",
       "NANI") AS MARDANI;

-- STRING LENGTH AND PADDING
-- (LENGTH, CHAR_LENGTH, CHARACTER_LENGTH, LPAD, RPAD)

SELECT  
      "MADARA UCHIHA" AS
      GHOST_OF_THE_UCHIHA,
             LENGTH("MADARA UCHIHA") AS
      LENGTH, 
            CHAR_LENGTH("MADARA UCHIHA") AS
            LENGTH,
      CHARACTER_LENGTH("MADARA UCHIHA") AS LENGTH;
      
SELECT 
      "MADARA UCHIHA THE GHOST OF THE UCHIHA" AS ORIGINAL_STRING,
      
      LENGTH("MADARA UCHIHA THE GHOST OF THE UCHIHA") AS LENGTH,
      
      REPLACE("MADARA UCHIHA THE GHOST OF THE UCHIHA", " ", " "),
      
      LENGTH(REPLACE("MADARA UCHIHA THE GHOST OF THE UCHIHA", " ", 
      " "));
      
SELECT *,
     (LENGTH(ORIGINAL_STRING) - 
     LENGTH(STRING_WITHOUT_SPACES)) AS 
     NUMBER_OF_SPACES
     FROM
     (
      SELECT 
            "MADARA UCHIHA THE GHOST OF THE UCHIHA" AS ORIGINAL_STRING,
            REPLACE("MADARA UCHIHA THE GHOST OF THE UCHIHA", " ", " ") AS
            STRING_WITHOUT_SPACES
     ) AS T;
     
     
SELECT 
      "MADARA UCHIHA THE GHOST OF THE UCHIHA" AS ORIGINAL_STRING,
      REPLACE("MADARA UCHIHA THE GHOST OF THE UCHIHA", " ", " ") AS
      STRING_WITHOUT_SPACES;
      
-- PADDING (BINARY VALUES)

SELECT 
       '33' AS DECIMAL_VALUE,
       '100001' AS BINARY_VALUE,
       LPAD('100001', 8, 0) AS
       LEFT_PADDED_VALUE,
          RPAD('100001',8, 0) AS
          RIGHT_PADDED_VALUE;
          
          
-- SUBSTRING FUNCTIONS
-- (LEFT, RIGHT MID, SUBSTR, SUBSTRING, SUBSTRING_INDEX)

SELECT 
     CURRENT_STRING,
     LEFT(CURRENT_STRING, 5),
     RIGHT(CURRENT_STRING, 6),
     MID(CURRENT_STRING, 7, 8),
     SUBSTR(CURRENT_STRING, 7, 8),
     SUBSTRING(CURRENT_STRING, 7, 8)
     
FROM
(
SELECT 'Orewa Namikaze Minato' AS CURRENT_STRING
) AS T;


-- SUBSTRING_INDEX

CREATE TABLE MAMAA AS 
SELECT 
	'WWW.META.COM' AS URL
UNION ALL 
SELECT 
	'WWW.ALPHABET.COM' AS URL
UNION ALL 
SELECT 
	'WWW.MICROSOFT.COM' AS URL
UNION ALL 
SELECT 
	'WWW.APPLE.COM' AS URL
UNION ALL 
SELECT 
	'WWW.AMAZON.COM' AS URL; 
    
SELECT *
FROM MAMAA;    

SELECT URL, SUBSTRING(URL, 5, 9)
FROM MAMAA;

SELECT 
      'WWW.META.COM' AS URL,
      SUBSTRING_INDEX('WWW.META.COM', '.', 1),
      SUBSTRING_INDEX('WWW.META.COM', '.', 2),
      SUBSTRING_INDEX('WWW.META.COM', '.', 3),
      SUBSTRING_INDEX('WWW.META.COM', '.', -1),
      SUBSTRING_INDEX('WWW.META.COM', '.', -2);
      
SELECT 
	'WWW.META.COM' AS URL, 
	SUBSTRING_INDEX('WWW.META.COM', '.', 2), 
    SUBSTRING_INDEX(SUBSTRING_INDEX('WWW.META.COM', '.', 2), '.', -1);
    
SELECT 
	'WWW.META.COM' AS URL,
    SUBSTRING_INDEX('WWW.META.COM', '.', -2), 
    SUBSTRING_INDEX(SUBSTRING_INDEX('WWW.META.COM', '.', -2), '.', 1); 
    
SELECT * FROM MAMAA;

SELECT 
	URL,
    SUBSTRING_INDEX(URL, '.', 2), 
    SUBSTRING_INDEX(SUBSTRING_INDEX(URL, '.', 2), '.', -1)
FROM MAMAA; 

SELECT URL, SUBSTRING(URL, 5), 
SUBSTRING_INDEX(SUBSTRING(URL, 5), '.', 1)   
FROM MAMAA; 


CREATE TABLE T1 AS
SELECT 
      'HTTPS://WWW.GOOGLE.COM' AS
      CURRENT_STRING
      UNION ALL
      SELECT 
           'WWW\.GOOGLE.COM' AS CURRENT_STRING
           UNION ALL
           SELECT 
                 'WWW.GOOGLE.CO.IN' AS CURRENT_STRING;
                 
SELECT * FROM T1;

SELECT 
     CURRENT_STRING,
     SUBSTRING_INDEX(CURRENT_STRING, '.', 2),
     
     SUBSTRING_INDEX(SUBSTRING_INDEX(CURRENT_STRING, '.', 2), '.', -1)
     FROM
     T1;
     
     -- TRIMMING FUNCTION (LTRIM, RTRIM, TRIM)
     
     
     SELECT 
	ORIGINAL_STRING, LENGTH(ORIGINAL_STRING)
    AS LENGTH_OF_ORIGINAL_STRING, 
	LTRIM(ORIGINAL_STRING) 
    AS LEFT_TRIMMED_STRING,  LENGTH(LTRIM(ORIGINAL_STRING))
    AS LENGTH_OF_LEFT_TRIMMED_STRING, 
    RTRIM(ORIGINAL_STRING) 
    AS RIGHT_TRIMMED_STRING, LENGTH(RTRIM(ORIGINAL_STRING)) 
    AS LENGTH_OF_RIGHT_TRIMMED_STRING, 
    TRIM(ORIGINAL_STRING)  
    AS BOTH_SIDE_TRIMMED_STRING, LENGTH(TRIM(ORIGINAL_STRING)) AS LENGTH_OF_BOTH_SIDE_TRIMMED_STRING
FROM 
(
SELECT 
	'    ABCD    ' AS ORIGINAL_STRING
) AS T; 


CREATE TABLE TRIMMING AS 
SELECT 'ORIGINAL STRING' AS STRING_TYPE, '    ABCD    ' AS ORIGINAL_STRING 
UNION ALL 
SELECT 'LEFT TRIMMED STRING' AS STRING_TYPE, LTRIM('    ABCD    ') AS ORIGINAL_STRING 
UNION ALL 
SELECT 'RIGHT TRIMMED STRING' AS STRING_TYPE, RTRIM('    ABCD    ') AS ORIGINAL_STRING 
UNION ALL 
SELECT 'BOTH SIDE TRIMMED STRING' AS STRING_TYPE, TRIM('    ABCD    ') AS ORIGINAL_STRING; 

SELECT * FROM TRIMMING;

SELECT STRING_TYPE, 
ORIGINAL_STRING, 
LENGTH(ORIGINAL_STRING) 
AS STRING_LENGTH
FROM TRIMMING; 

SELECT 
	'000SLDGHLSDJGSDL000' AS IMPORTANT_CODE,
    TRIM(LEADING '0' FROM '000SLDGHLSDJGSDL000') AS NEW_CODE, 
    TRIM(TRAILING '0' FROM '000SLDGHLSDJGSDL000') AS NEW_CODE, 
	TRIM(BOTH '0' FROM '000SLDGHLSDJGSDL000') AS NEW_CODE ; 
    
    
    -- REVERSE STRING.
    
   SELECT 
	'KARAN' AS ORIGINAL_STRING, 
    REVERSE('KARAN') AS REVERSED_STRING;

    SELECT ASCII("A");

 